# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8c6b3d26c41b4074a16cefc03b3494b89d5ec544cfe333bacec202ba43099b600f46b35c42c40d82bdf09b2470528816079a544b0b1615d25c392bb593fa674

test:
  secret_key_base: 48608ed359115a0499b09f342f3d9daae63d3a10c6aeacd56944e2a18b5777ffc02dff3f8dedaa9c5bd550bca8aeb35bdbc72120781c4d4cedef2ddc0c78c813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
